[package]
name = "uksirius"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.7", features = ["v4", "fast-rng"] }
md5 = "0.7"
rand = "0.8"
